In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
## Define the vocabulary size
voc_size=10000

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
[words.split(' ') for words in sent]

[['the', 'glass', 'of', 'milk'],
 ['the', 'glass', 'of', 'juice'],
 ['the', 'cup', 'of', 'tea'],
 ['I', 'am', 'a', 'good', 'boy'],
 ['I', 'am', 'a', 'good', 'developer'],
 ['understand', 'the', 'meaning', 'of', 'words'],
 ['your', 'videos', 'are', 'good']]

In [8]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4738, 9126, 3474, 7307],
 [4738, 9126, 3474, 1579],
 [4738, 6982, 3474, 1853],
 [7841, 707, 6067, 5711, 775],
 [7841, 707, 6067, 5711, 2477],
 [6872, 4738, 6030, 3474, 36],
 [1164, 7219, 886, 5711]]

In [9]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4738 9126 3474 7307]
 [   0    0    0    0 4738 9126 3474 1579]
 [   0    0    0    0 4738 6982 3474 1853]
 [   0    0    0 7841  707 6067 5711  775]
 [   0    0    0 7841  707 6067 5711 2477]
 [   0    0    0 6872 4738 6030 3474   36]
 [   0    0    0    0 1164 7219  886 5711]]


In [12]:
## feature representation
dim=10

In [15]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','categorical_crossentropy')

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
op_embeddings=model.predict(embedded_docs)
print(op_embeddings.shape)
op_embeddings

1/1 [==============================] - 0s 42ms/step
(7, 8, 10)


array([[[-0.0071754 , -0.04399258, -0.0085879 ,  0.0302974 ,
         -0.04503167, -0.03786464,  0.04120215,  0.02773017,
          0.02036724, -0.01986489],
        [-0.0071754 , -0.04399258, -0.0085879 ,  0.0302974 ,
         -0.04503167, -0.03786464,  0.04120215,  0.02773017,
          0.02036724, -0.01986489],
        [-0.0071754 , -0.04399258, -0.0085879 ,  0.0302974 ,
         -0.04503167, -0.03786464,  0.04120215,  0.02773017,
          0.02036724, -0.01986489],
        [-0.0071754 , -0.04399258, -0.0085879 ,  0.0302974 ,
         -0.04503167, -0.03786464,  0.04120215,  0.02773017,
          0.02036724, -0.01986489],
        [ 0.00844941,  0.03140098, -0.00878962,  0.00735307,
         -0.04263349,  0.04606182,  0.01737461,  0.04332111,
          0.0214704 ,  0.00337923],
        [-0.01337845, -0.00084234,  0.02012238,  0.02080008,
         -0.0432169 , -0.01799113, -0.04882306,  0.02307154,
         -0.03025897,  0.01882948],
        [-0.03259265, -0.03112508,  0.02823665,  0.0

In [20]:
embedded_docs[0]

array([   0,    0,    0,    0, 4738, 9126, 3474, 7307])

In [25]:
op_embeddings.shape[0]

7

In [27]:
for sent in range(op_embeddings.shape[0]):
    print("checkin {} sentence".format(sent))
    for word in range(op_embeddings.shape[1]):
        print(op_embeddings[sent][word])


checkin 0 sentence
[-0.0071754  -0.04399258 -0.0085879   0.0302974  -0.04503167 -0.03786464
  0.04120215  0.02773017  0.02036724 -0.01986489]
[-0.0071754  -0.04399258 -0.0085879   0.0302974  -0.04503167 -0.03786464
  0.04120215  0.02773017  0.02036724 -0.01986489]
[-0.0071754  -0.04399258 -0.0085879   0.0302974  -0.04503167 -0.03786464
  0.04120215  0.02773017  0.02036724 -0.01986489]
[-0.0071754  -0.04399258 -0.0085879   0.0302974  -0.04503167 -0.03786464
  0.04120215  0.02773017  0.02036724 -0.01986489]
[ 0.00844941  0.03140098 -0.00878962  0.00735307 -0.04263349  0.04606182
  0.01737461  0.04332111  0.0214704   0.00337923]
[-0.01337845 -0.00084234  0.02012238  0.02080008 -0.0432169  -0.01799113
 -0.04882306  0.02307154 -0.03025897  0.01882948]
[-0.03259265 -0.03112508  0.02823665  0.00141927 -0.03953508  0.0085574
 -0.04334999 -0.00456903  0.03781635  0.01229197]
[ 0.03168334 -0.02643669 -0.0210967   0.02752615 -0.00329702 -0.0005088
  0.02840335  0.01663152  0.04980525 -0.0165146 ]